# Generated by Django 3.2.19 on 2023-05-09 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230509_1437'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
